public enum TokenType {
        NUMBER, IDENTIFIER, ASSIGN, PLUS, MINUS, MULTIPLY, DIVIDE, MODULO,
        IF, ELSE, WHILE, PRINT, LBRACKET, RBRACKET, LBRACE, RBRACE, SEMICOLON,
        COMMA, EQUALS, NOT_EQUALS, GREATER_THAN, LESS_THAN, GREATER_THAN_OR_EQUAL,
        LESS_THAN_OR_EQUAL, LOGICAL_AND, LOGICAL_OR, LOGICAL_NOT, INCREMENT,
        DECREMENT, EOF, ERROR
}
//comments here
